distribuidor/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^login/$', 'distribuidor.views.login_view', name='login'),
                       url(r'^logout/$', 'distribuidor.views.logout_view', name='logout'),
                       url(r'^pwd_reset/(?P<username>\d+)/(?P<hash_val>.+)/$', 'distribuidor.views.password_user_reset', name='password_user_reset'),
                       )

vendas/urls.py
from django.conf.urls import patterns, url
from vendas.views import PedidosList


urlpatterns = patterns('',
                       url(r'^pedidos/$', PedidosList.as_view(), name='pedidos_list'),
                       url(r'^pedidos/add/$', 'vendas.views.pedido_add', name='pedidos_add'),
                       url(r'^pedidos/(?P<pk>\d+)/$', 'vendas.views.pedidos_up', name='pedidos_up'),
                       )

zumbets/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'appconfig.views.index', name='index'),
    url(r'', include(frontend_urls)),
    url(r'', include('distribuidor.urls')),
    url(r'', include('vendas.urls')),

    # url(r'^media/(?<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
]

distribuidor/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models
from django.db import transaction

from comissao.models import Nivel, Comissao, DetalheComissao
from vendas.models import Pedido


CHOICES_SEXO = (('m', 'Masculino'),
                ('f', 'Feminino'),
                )

CHOICES_UNIDADE_FEDERATIVA = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AM', 'Amazonas'),
    ('AP', 'Amapá'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraiba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergige'),
    ('TO', 'Tocantins'),
)

class Pessoa(User):
    cpf = models.CharField(max_length=11, verbose_name='CPF', unique=True)
    data_nascimento = models.DateField(verbose_name='Data Nascimento')
    sexo = models.CharField(max_length=1, verbose_name='Sexo', choices=CHOICES_SEXO)
    rg = models.CharField(max_length=30, verbose_name='RG')
    orgao_emissor = models.CharField(max_length=30, verbose_name='Orgão Emissor')
    estado = models.CharField(max_length=2, verbose_name='Estado', choices=CHOICES_UNIDADE_FEDERATIVA)
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    cep = models.PositiveIntegerField(verbose_name='CEP')
    endereco = models.CharField(max_length=100, verbose_name='Endereço')
    telefone1 = models.CharField(max_length=16, verbose_name='Telefone1')
    telefone2 = models.CharField(max_length=16, verbose_name='Telefone2', blank=True, null=True)
    # nivel = models.ForeignKey('comissao.Nivel', verbose_name='Nivel')
    classe = models.ForeignKey('comissao.Classe', verbose_name='Classe')
    recrutador = models.ForeignKey('distribuidor.Pessoa', verbose_name='Recrutador', null=True, blank=True)
    exp = models.BigIntegerField(verbose_name='Experiência')

    def __unicode__(self):
        return '%s' % self.get_full_name()

    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    def set_exp(self, exp):
        self.exp = self.exp + exp
        self.save()

    def calcula_comissao(self):
        try:
            #Cacula vendas diretas
            pedidos_vendas_diretas = Pedido.objects.filter(distribuidor=self.id, status=3)
            valor_vendas_diretas = 0

            for venda in pedidos_vendas_diretas:
                valor_vendas_diretas += venda.get_preco_pedido()

            per_comissao_direta = Nivel.objects.filter(classe=self.classe,
                                                       exp_minima__lte=valor_vendas_diretas,
                                                       exp_maxima__gte=valor_vendas_diretas).first().comissao

            comissao_venda_direta = float(valor_vendas_diretas*per_comissao_direta/100)

            with transaction.atomic():
                comissao = Comissao.objects.create(pessoa=self, comissao=0)
                comissao.save()
                for venda in pedidos_vendas_diretas:
                    detalhe_comissao = DetalheComissao.objects.create(comissao=comissao, pedido=venda,
                                                                      valor=venda.get_preco_pedido(),
                                                                      percentual=per_comissao_direta, tipo=1,
                                                                      valor_comissao=float(venda.get_preco_pedido()*per_comissao_direta/100))
                    detalhe_comissao.save()

                # Calcula a comissao dos recrutas do primeiro nivel da arvore
                pedidos_vendas_recrutas_1 = Pedido.objects.filter(distribuidor__in=Pessoa.objects.filter(recrutador=self.id), status=3)
                valor_vendas_recrutas_1 = 0

                for venda in pedidos_vendas_recrutas_1:
                    valor_vendas_recrutas_1 += venda.get_preco_pedido()

                per_comissao_recrutas_1 = 3

                comissao_venda_recrutas_1 = float(valor_vendas_recrutas_1*per_comissao_recrutas_1/100)

                for venda in pedidos_vendas_recrutas_1:
                    detalhe_comissao = DetalheComissao.objects.create(comissao=comissao, pedido=venda,
                                                                      valor=venda.get_preco_pedido(),
                                                                      percentual=per_comissao_recrutas_1, tipo=2,
                                                                      valor_comissao=float(venda.get_preco_pedido()*per_comissao_recrutas_1/100))
                    detalhe_comissao.save()

                # Calcula a comissao dos recrutas do segundo nivel da arvore
                pedidos_vendas_recrutas_2 = Pedido.objects.filter(distribuidor__in=Pessoa.objects.filter(recrutador__in=Pessoa.objects.filter(recrutador=self.id)), status=3)
                valor_vendas_recrutas_2 = 0

                for venda in pedidos_vendas_recrutas_2:
                    valor_vendas_recrutas_2 += venda.get_preco_pedido()

                per_comissao_recrutas_2 = 2

                comissao_venda_recrutas_2 = float(valor_vendas_recrutas_2*per_comissao_recrutas_2/100)

                for venda in pedidos_vendas_recrutas_2:
                    detalhe_comissao = DetalheComissao.objects.create(comissao=comissao, pedido=venda,
                                                                      valor=venda.get_preco_pedido(),
                                                                      percentual=per_comissao_recrutas_2, tipo=3,
                                                                      valor_comissao=float(venda.get_preco_pedido()*per_comissao_recrutas_2/100))
                    detalhe_comissao.save()

                # Calcula a comissao dos recrutas do Terceiro nivel da arvore
                pedidos_vendas_recrutas_3 = Pedido.objects.filter(distribuidor__in=Pessoa.objects.filter(recrutador__in=Pessoa.objects.filter(recrutador__in=Pessoa.objects.filter(recrutador=self.id))), status=3)
                valor_vendas_recrutas_3 = 0

                for venda in pedidos_vendas_recrutas_3:
                    valor_vendas_recrutas_3 += venda.get_preco_pedido()

                per_comissao_recrutas_3 = 1

                comissao_venda_recrutas_3 = float(valor_vendas_recrutas_3*per_comissao_recrutas_3/100)

                for venda in pedidos_vendas_recrutas_3:
                    detalhe_comissao = DetalheComissao.objects.create(comissao=comissao, pedido=venda,
                                                                      valor=venda.get_preco_pedido(),
                                                                      percentual=per_comissao_recrutas_3, tipo=4,
                                                                      valor_comissao=float(venda.get_preco_pedido()*per_comissao_recrutas_3/100))
                    detalhe_comissao.save()

                comissao.comissao = comissao_venda_direta + comissao_venda_recrutas_1 + comissao_venda_recrutas_2 + comissao_venda_recrutas_3
                comissao.save()

                return 'sucesso'
        except Exception, e:
            return e


def validate_cpf(cpf):
    cpf_invalidos = [11 * str(i) for i in range(10)]
    if cpf in cpf_invalidos:
        return False

    if not cpf.isdigit():
        """ Verifica se o CPF contem pontos e hifens """
        cpf = cpf.replace('.', '').replace('-', '')

    if len(cpf) < 11:
        """ Verifica se o CPF tem 11 digitos """
        return False

    if len(cpf) > 11:
        """ CPF tem que ter 11 digitos """
        return False

    selfcpf = [int(x) for x in cpf]

    cpf = selfcpf[:9]

    while len(cpf) < 11:

        r = sum([(len(cpf) + 1 - i) * v for i, v in [(x, cpf[x]) for x in range(len(cpf))]]) % 11

        if r > 1:
            f = 11 - r
        else:
            f = 0
        cpf.append(f)

    return bool(cpf == selfcpf)

distribuidor/forms.py
# coding=utf-8
from django import forms
from distribuidor.models import Pessoa, validate_cpf


class LoginForm(forms.Form):
    username = forms.CharField(label='CPF', required=False)
    password = forms.CharField(label='Senha', widget=forms.PasswordInput, required=False)


class PasswordResetForm(forms.Form):
    cpf = forms.CharField(label='CPF', required=True)
    email = forms.EmailField(label='E-mail', max_length=254)


class PasswordResetUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Nova Senha', widget=forms.PasswordInput, min_length=4, required=True)
    password2 = forms.CharField(label='Digite novamente a senha', widget=forms.PasswordInput, min_length=4, required=True)

    class Meta:
        model = Pessoa
        fields = ['password1', 'password2']

    def save(self, commit=False):
        pessoa = super(PasswordResetUserForm, self).save(commit=commit)
        pessoa.set_password(self.cleaned_data['password1'])
        pessoa.save()
        return pessoa

    def clean(self):
        cleaned_data = super(PasswordResetUserForm, self).clean()

        if cleaned_data['password1'] != cleaned_data['password2']:
            msg_pwd = 'As duas senhas não conferem!. Por favor, confira os dados digitados.'
            self._errors['password1'] = msg_pwd
            self._errors['password2'] = msg_pwd
            raise forms.ValidationError('As duas senhas não conferem!. Por favor, confira os dados digitados.')
        return cleaned_data


class PasswordChangeForm(forms.ModelForm):

    password_old = forms.CharField(label='Senha Atual', widget=forms.PasswordInput, min_length=4, required=True)
    password1 = forms.CharField(label='Nova Senha', widget=forms.PasswordInput, min_length=4, required=True)
    password2 = forms.CharField(label='Digite novamente a senha', widget=forms.PasswordInput, min_length=4, required=True)

    class Meta:
        model = Pessoa
        fields = ['password_old', 'password1', 'password2']

    def save(self, commit=False):
        pessoa = super(PasswordChangeForm, self).save(commit=commit)
        pessoa.set_password(self.cleaned_data['password1'])
        pessoa.save()
        return pessoa

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        user = super(PasswordChangeForm, self).save(commit=False)

        if not user.check_password(cleaned_data['password_old']):
            self._errors['password_old'] = 'Senha incorreta'
            raise forms.ValidationError('A senha atual esta incorreta! Por favor, tente novamente')

        if cleaned_data['password_old'] == cleaned_data['password1']:
            self._errors['password1'] = 'A Nova Senha de ser diferente da Senha Atual.'
            raise forms.ValidationError('A Nova Senha de ser diferente da Senha Atual. Por favor confira os dados digitados.')

        if cleaned_data['password1'] != cleaned_data['password2']:
            msg_pwd = 'As duas senhas não conferem!. Por favor, confira os dados digitados.'
            self._errors['password1'] = msg_pwd
            self._errors['password2'] = msg_pwd
            raise forms.ValidationError('As duas senhas não conferem!. Por favor, confira os dados digitados.')

        return cleaned_data


class PessoaForm(forms.ModelForm):
    first_name = forms.CharField(label='Primeiro Nome', required=True)
    last_name = forms.CharField(label='Sobrenome', required=True)
    email = forms.CharField(label='E-mail', required=True)


    class Meta:
        model = Pessoa
        fields = '__all__'

    def save(self, commit=False):
        pessoa = super(PessoaForm, self).save(commit=commit)
        if not pessoa.id:
            pessoa.set_password('zumbeats@'+pessoa.cpf[:3])
            pessoa.username = pessoa.cpf
        pessoa.save()

        return pessoa

    def clean(self):
        data = super(PessoaForm, self).clean()

        if not validate_cpf(data.get('cpf')):
            self._errors['cpf'] = u'CPF inválido'

        return data

distribuidor/templates/email_reset_password.html
<div class="container" style="max-width: 600px; font-family: 'Roboto', sans-serif;">

    <br>

    <div class="row" id="corpo" style="text-align: left">
        <div class="row" id="cabecalho">
            <div class="col s12" style="text-align: center">
{#                <img width="80" height="80" src="http://www.palmas.to.gov.br/static/base/img/brasao.png"><br/>#}
                    <span class="card-title black-text" style="line-height: 18px; font-size: 14px;">
                    <strong>ZUMBEATS</strong>
                </span>
            </div>
        </div>
        <div> <br> <br> </div>
        <div>
            <a href="{{ link }}">{{ frase }}.</a>
        </div>
        <div><br></div>
        <div>
            <p>Ou copie e cole este link no seu navegador: {{ link }}</p>
        </div>

    </div>
</div>

distribuidor/templates/login.html
{% extends 'base.html' %}

{% block content %}
        <div class="row" style="margin-top: 100px">
            <div class="col s12 offset-l2 l8">
                {% if msg_sucess %}
                    <div class="card-panel green lighten-1">
                        <span>{{ msg_sucess }}</span>
                    </div>
                {% endif %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title grey-text text-darken-4">
                            <h4>Login</h4>
                        </span>
                        {% if msg_error %}
                            <div class="row">
                                <div class="card-panel red lighten-2 white-text">
                                  <p> {{ msg_error }} </p>
                                </div>
                            </div>
                        {% endif %}

                        {% if form.non_field_errors %}
                            <div class="card-panel red lighten-2 white-text">
                                {% for error in form.non_field_errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <form method="post" id="login-form">
                            {% csrf_token %}
                            <input type="hidden" name="submit_login" value="True" />
                            <input type="hidden" name="next" value="{{ next }}" />
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">person</i>
                                    {{ form.username }}
                                    {{ form.username.label_tag }}
                                    {% if form.username.errors %}
                                        <span class="red-text">{{ form.username.errors }}</span>
                                    {% endif %}
                                </div>
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">vpn_key</i>
                                    {{ form.password }}
                                    {{ form.password.label_tag }}
                                    {% if form.password.errors %}
                                        <span class="red-text">{{ form.password.errors }}</span>
                                    {% endif %}
                                </div>
                            </div>
                            <p class="right-align">
                                <button type="submit" class="waves-effect waves-light btn" onclick="$('#tipo_submit').val(0)">
                                    <i class="material-icons right">input</i>Entrar
                                </button>
                            </p>
                        </form>
                    </div>

{#                    {% url 'password_user_reset' as password_reset %}#}
                    <div class="card-reveal" {% if msg_reset or form_reset.non_field_errors or form_reset.cpf.errors or form_reset.email.errors%}style="display: block;transform: translateY(-100%);"{% endif %}>
                        <span class="card-title grey-text text-darken-4">Recuperar a senha<i class="material-icons right">close</i></span>
                        <p>Esqueceu sua senha? Digite seu CPF e endereço de e-mail abaixo , e vamos enviar instruções para configurar uma nova.</p>

                        {% if msg_reset %}
                            <div class="card-panel red lighten-2 white-text">
                                <span>{{ msg_reset|safe }}</span>
                            </div>
                        {% endif %}

                        {% if form_reset.non_field_errors %}
                            <div class="card-panel red lighten-2 white-text">
                                {% for error in form_reset.non_field_errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <form action="." method="post">
                            {% csrf_token %}
                            <input type="hidden" name="submit_reset" value="True"/>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">person</i>
                                    {{ form_reset.cpf }}
                                    <label for="id_cpf">CPF</label>
                                    {% if form_reset.cpf.errors %}
                                        <span class="red-text">{{ form_reset.cpf.errors }}</span>
                                    {% endif %}
                                </div>

                                <div class="input-field col s12">
                                    <i class="material-icons prefix">email</i>
                                    {{ form_reset.email }}
                                    <label for="id_email">E-mail</label>
                                    {% if form_reset.email.errors %}
                                        <span class="red-text">{{ form_reset.email.errors }}</span>
                                    {% endif %}
                                </div>
                                <div class="input-field col s12">
                                    <button type="submit" value="Enviar" class="waves-effect waves-light btn right">
                                        <i class="material-icons right">send</i>Enviar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-action">
                        <a href="#" class="activator">Esqueceu sua senha?</a>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('#id_username').focus().trigger();
        })
    </script>
{% endblock %}

distribuidor/templates/password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div><br><br><br><br></div>
<div class="container">
    <div class="row">
        <div class="col s12 m12 l8">
            {% if form.non_field_errors %}
                <div class="form_errors alert alert-danger">
                    {% for err in form.non_field_errors %}
                        <div class="card-panel red lighten-1 white-text">{{ err }}</div>
                    {% endfor %}
                </div>
            {% endif %}

            {% if form %}
                <div class="card">
                    <form action="" method="post">
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-4">
                                <h4>{{ titulo }}</h4>
                            </span>
                            {% csrf_token %}
                            <div class="row">
                                {% for field in form %}
                                    {% if not field.is_hidden %}
                                        <div class="input-field col s12 m12 l12">
                                            <i class="material-icons prefix">vpn_key</i>
                                            {{ field }}
                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {% if field.errors %}
                                                <span class="help-block" style="color: #B94A48; font-size: 12px">{{ field.errors|safe  }}</span>
                                            {% endif %}
                                        </div>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="card-action">
                            <p class="right-align">
                                <button type="submit" class="waves-effect waves-light btn">
                                    <i class="material-icons right">save</i>Salvar
                                </button>
                            </p>
                        </div>
                    </form>
                </div>
            {% else %}
                 <div class="card red lighten-1">
                    <div class="card-content white-text">
                        <span class="card-title"><b>A redefinição de senha falhou!</b></span>
                        <p>{{ msg_erro }}</p>
                    </div>
                    <div class="card-action">
                        <a class="black-text" href="#">
                            <i class="material-icons left">email</i>
                            Reenviar email</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
    <br><br><br><br>
{% endblock %}

distribuidor/templates/pessoa_password_change.html
{% extends 'base.html' %}

{% block content %}

    <h3>{{ titulo }}</h3>

    <div class="row">
        {% if form.non_field_errors %}
            <div class="form_errors alert alert-danger">
                {% for err in form.non_field_errors %}
                    <div class="card-panel red lighten-1 white-text">{{ err }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <form action=""method="post">
            <fieldset class="z-depth-1">

                {% csrf_token %}

                {% for field in form %}
                    {% if not field.is_hidden %}
                        <div class="input-field col s12 m12 l12">
                            {{ field }}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {% if field.errors %}
                                <span class="help-block" style="color: #B94A48; font-size: 12px">{{ field.errors|safe  }}</span>
                            {% endif %}
                        </div>
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

            </fieldset>

            <div class="fixed-action-btn" style="bottom: 4%; right: 8%;">
                <button class="btn-floating btn-large green z-depth-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Salvar" type="submit">
                  <i class="large material-icons">save</i>
                </button>
            </div>
        </form>
            <div class="col s1 fixed-action-btn " style="bottom: 4%; left: 8%;">
                <a href="{% url 'pessoa_list' %}" class="tooltipped" data-position="left" data-delay="10" data-tooltip="Voltar">
                    <button class="btn-floating btn-large  waves-effect waves-light z-depth-2"><i class="material-icons">keyboard_arrow_left</i></button>
                </a>
            </div>
    </div>
    <br><br><br><br>
{% endblock %}